### ISSUE TITLE
Find results in a buffer

### ISSUE THREAD

**Issue by levsa** [leonid-shevtsov/SearchInProject_SublimeText#15] opened 2014-04-02 11:08 UTC
It would be nice to have the search results in a buffer or a window instead of a dialog. One can go back to the window and open several search results that way. Similar to the built in "Find in files..." command.

**Comment by leonid-shevtsov** [comment] 2015-02-14 21:03
Closing as duplicate of #6, I'll track progress there.

**Closed by leonid-shevtsov** 2015-02-14 21:03 UTC
